### PR TITLE
Package this project with nix and flakes

### PR DESCRIPTION
**Pull request by ggazzi**
This allows people to install this via nix, but also to easily build and package utilities based on this via nix.

### CODE REVIEW

**Comment by juanibiapina** [comment]
This is awesome Gui! I really like how easy it is to generate your own CLI. One thing we could change is specify that it needs to be either:

1. `bin` and `relative`
2. `absolute`

Perhaps clap can even do that for us with https://docs.rs/clap/latest/clap/_derive/_tutorial/index.html#argument-relations

**Comment by juanibiapina** [comment]
This `bin` and `relative` trick exists so I can do this in both OSX and Linux:

```
sub --name dev --bin "${BASH_SOURCE[0]}" --relative ".." -- "$@"
```

**Comment by ggazzi** [comment]
I like the idea of using a Clap::ArgGroup, but this is not possible in the (very outdated) version of Clap that is being used for now.

I'll make another PR updating Clap and we can come back to this after that.

**Comment by ggazzi** [comment]
Also, it would be good to test the new options, but I don't quite understand how the fixtures work and didn't find good documentation on it. @juanibiapina could you look into that?

**Comment by juanibiapina** [comment]
Então. Isso que da fazer as coisas de férias. Eu queria só fazer o merge desse PR e deixar o clap 4 pra depois e fiz errado.

**Pull request merged**
